<a href="https://colab.research.google.com/github/vignesh200010/highIQpython/blob/main/final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
# // There are a bunch of documents that belong to the same type - Invoices from an LTC (Long Term Care)  business team. The major variation from these docs is that there are multiple tables in each document, but the business is interested only in a specific table that has a certain type of information

# // 1.png: There are multiple tables under the ‘Current Activity’ section. But the business is interested only in the last one because that has the date, description, qty, rate, and amount information
# // 2.png: Again there are multiple boxed tables but the biz needs only the last one that has the date, description, qty, rate, and amount information
# // 3.png: Same as the above 2 and biz is interested only in the last table that has the date, description, qty, rate, and amount information

# New_cols == description
# From Date
# to Date 
# Quantity qty
# rate rate
# Amount  Amount 

string_1 = '''[
  {
    "table": {
      "cols": [
        "New Charges",
        "From",
        "To",
        "Quantity",
        "Rate",
        "Frequency",
        "Amount"
      ],
      "rows": [
        [
          "Bar Charges",
          "12/29/19",
          "12/29/19",
          "1.00",
          "$71.65",
          "One time",
          "$71.65"
        ],
        [
          "Dining Services",
          "12/31/19",
          "12/31/19",
          "1.00",
          "$17.90",
          "One time",
          "$17.90"
        ],
        [
          "Incontinence supplies",
          "12/18/19",
          "12/18/19",
          "1.00",
          "$55.32",
          "One time",
          "$55.32"
        ],
        [
          "Bar Charges",
          "01/11/20",
          "01/11/20",
          "1.00",
          "$73.75",
          "One time",
          "$73.75"
        ],
        [
          "Room - Assisted Living",
          "02/01/20",
          "02/29/20",
          "1.00",
          "$4,695.00",
          "Monthly",
          "$4,695.00"
        ],
        [
          "Assisted Living Level 3",
          "02/01/20",
          "02/29/20",
          "1.00",
          "$1,700.00",
          "Monthly",
          "$1,700.00"
        ],
        [
          "Basic Medication Management",
          "02/01/20",
          "02/29/20",
          "1.00",
          "$275.00",
          "Monthly",
          "$275.00"
        ],
        [
          "Emergency Response Charge",
          "02/01/20",
          "02/29/20",
          "1.00",
          "$30.00",
          "Monthly",
          "$30.00"
        ]
      ],
      "bbox": [
        118,
        1219,
        2371,
        1691
      ],
      "data": [
        [
          "New Charges",
          "From",
          "To",
          "Quantity",
          "Rate",
          "Frequency",
          "Amount"
        ],
        [
          "Bar Charges",
          "12/29/19",
          "12/29/19",
          "1.00",
          "$71.65",
          "One time",
          "$71.65"
        ],
        [
          "Dining Services",
          "12/31/19",
          "12/31/19",
          "1.00",
          "$17.90",
          "One time",
          "$17.90"
        ],
        [
          "Incontinence supplies",
          "12/18/19",
          "12/18/19",
          "1.00",
          "$55.32",
          "One time",
          "$55.32"
        ],
        [
          "Bar Charges",
          "01/11/20",
          "01/11/20",
          "1.00",
          "$73.75",
          "One time",
          "$73.75"
        ],
        [
          "Room - Assisted Living",
          "02/01/20",
          "02/29/20",
          "1.00",
          "$4,695.00",
          "Monthly",
          "$4,695.00"
        ],
        [
          "Assisted Living Level 3",
          "02/01/20",
          "02/29/20",
          "1.00",
          "$1,700.00",
          "Monthly",
          "$1,700.00"
        ],
        [
          "Basic Medication Management",
          "02/01/20",
          "02/29/20",
          "1.00",
          "$275.00",
          "Monthly",
          "$275.00"
        ],
        [
          "Emergency Response Charge",
          "02/01/20",
          "02/29/20",
          "1.00",
          "$30.00",
          "Monthly",
          "$30.00"
        ]
      ]
    }
  },
  {
    "table": {
      "cols": [
        "Payments",
        "Date",
        "",
        "",
        "",
        "Amount"
      ],
      "rows": [
        [
          "Electronic payment",
          "12/30/19",
          "12/30/19",
          "1.00",
          "$6,997.32One time",
          "($6,997.32)"
        ]
      ],
      "bbox": [
        114,
        957,
        2374,
        1053
      ],
      "data": [
        [
          "Payments",
          "Date",
          "",
          "",
          "",
          "Amount"
        ],
        [
          "Electronic payment",
          "12/30/19",
          "12/30/19",
          "1.00",
          "$6,997.32One time",
          "($6,997.32)"
        ]
      ]
    }
  },
  {
    "table": {
      "cols": [
        "Credits",
        "From",
        "To",
        "Quantity",
        "Rate",
        "Frequency",
        "Amount"
      ],
      "rows": [
        [
          "n/a",
          "n/a",
          "n/a",
          "n/a",
          "n/a",
          "n/a",
          "$0.00"
        ]
      ],
      "bbox": [
        117,
        1087,
        2382,
        1200
      ],
      "data": [
        [
          "Credits",
          "From",
          "To",
          "Quantity",
          "Rate",
          "Frequency",
          "Amount"
        ],
        [
          "n/a",
          "n/a",
          "n/a",
          "n/a",
          "n/a",
          "n/a",
          "$0.00"
        ]
      ]
    }
  }
]'''

string_2 = '''[
  {
    "table": {
      "cols": [
        "Services Description",
        "Hours",
        "Pay Rate",
        "Total"
      ],
      "rows": [
        [
          "LPN Services",
          "",
          "",
          ""
        ],
        [
          "February 17th 2020 08:00 am - 08:00 pm",
          "12",
          "$49.95/hour",
          "$599.40"
        ],
        [
          "Holiday: President's Day",
          "",
          "",
          "$299.70"
        ],
        [
          "February 17th 2020 08:00 pm - 08:00 am",
          "12",
          "$49.95/hour",
          "$599.40"
        ],
        [
          "Holiday: President's Day",
          "",
          "",
          "$99.90"
        ]
      ],
      "bbox": [
        120,
        2294,
        2431,
        2943
      ],
      "data": [
        [
          "Services Description",
          "Hours",
          "Pay Rate",
          "Total"
        ],
        [
          "LPN Services",
          "",
          "",
          ""
        ],
        [
          "February 17th 2020 08:00 am - 08:00 pm",
          "12",
          "$49.95/hour",
          "$599.40"
        ],
        [
          "Holiday: President's Day",
          "",
          "",
          "$299.70"
        ],
        [
          "February 17th 2020 08:00 pm - 08:00 am",
          "12",
          "$49.95/hour",
          "$599.40"
        ],
        [
          "Holiday: President's Day",
          "",
          "",
          "$99.90"
        ]
      ]
    }
  },
  {
    "table": {
      "cols": [
        "LPN",
        "Position",
        "Payment Terms",
        "Due Date"
      ],
      "rows": [
        [
          "Marie Liverpool",
          "",
          "",
          ""
        ],
        [
          "Marina Burnett",
          "",
          "",
          ""
        ],
        [
          "Tashana Johnson Gabriela Fernandez Tameka Williams",
          "Licensed Practical Nurse",
          "Due on receipt",
          "Due on receipt"
        ]
      ],
      "bbox": [
        121,
        1095,
        2434,
        1504
      ],
      "data": [
        [
          "LPN",
          "Position",
          "Payment Terms",
          "Due Date"
        ],
        [
          "Marie Liverpool",
          "",
          "",
          ""
        ],
        [
          "Marina Burnett",
          "",
          "",
          ""
        ],
        [
          "Tashana Johnson Gabriela Fernandez Tameka Williams",
          "Licensed Practical Nurse",
          "Due on receipt",
          "Due on receipt"
        ]
      ]
    }
  }
]'''

string_3 = '''[
  {
    "table": {
      "cols": [
        "Date",
        "Invoice #"
      ],
      "rows": [
        [
          "12/20/2019",
          "16553"
        ],
        [
          "",
          ""
        ]
      ],
      "bbox": [
        1882,
        281,
        2442,
        481
      ],
      "data": [
        [
          "Date",
          "Invoice #"
        ],
        [
          "12/20/2019",
          "16553"
        ],
        [
          "",
          ""
        ]
      ]
    }
  },
  {
    "table": {
      "cols": [
        "P.O. No.",
        "Terms",
        "Project"
      ],
      "rows": [
        [
          "",
          "",
          ""
        ]
      ],
      "bbox": [
        1350,
        1119,
        2430,
        1328
      ],
      "data": [
        [
          "P.O. No.",
          "Terms",
          "Project"
        ],
        [
          "",
          "",
          ""
        ]
      ]
    }
  },
  {
    "table": {
      "cols": [
        "Description",
        "Qty",
        "Rate",
        "Amount"
      ],
      "rows": [
        [
          "Twenty Two Days of Adult Day Care in January",
          "22",
          "115.00",
          "2,530.00"
        ],
        [
          "Dates: Jan 2nd. 3rd, 6th. 7th. 8th. 9th. 10th. 13th. 14th, 15th, 16th, 17th. 20th. 21st. 22nd. 23rd. 24th, 27th, 28th. 29th. 30th & 31st",
          "",
          "",
          ""
        ],
        [
          "JR House will be closed January Ist",
          "",
          "",
          ""
        ],
        [
          "Payment is due Jan 2nd",
          "",
          "",
          ""
        ],
        [
          "",
          "",
          "",
          ""
        ]
      ],
      "bbox": [
        173,
        1303,
        2425,
        2730
      ],
      "data": [
        [
          "Description",
          "Qty",
          "Rate",
          "Amount"
        ],
        [
          "Twenty Two Days of Adult Day Care in January",
          "22",
          "115.00",
          "2,530.00"
        ],
        [
          "Dates: Jan 2nd. 3rd, 6th. 7th. 8th. 9th. 10th. 13th. 14th, 15th, 16th, 17th. 20th. 21st. 22nd. 23rd. 24th, 27th, 28th. 29th. 30th & 31st",
          "",
          "",
          ""
        ],
        [
          "JR House will be closed January Ist",
          "",
          "",
          ""
        ],
        [
          "Payment is due Jan 2nd",
          "",
          "",
          ""
        ],
        [
          "",
          "",
          "",
          ""
        ]
      ]
    }
  }
]
'''

In [37]:
import json
import re

In [38]:
import json
string1_dict = json.loads(string_1)
string2_dict = json.loads(string_2)
string3_dict = json.loads(string_3)

In [4]:
type(string1_dict)

list

In [16]:
string_1 = '''[
  {
    "table": {
      "cols": [
        "New Charges",
        "From",
        "To",
        "Quantity",
        "Rate",
        "Frequency",
        "Amount"
      ],

cols=string1_dict[0]['table']['cols']
all_rows=string1_dict[0]['table']['rows']
res=[]
for x in all_rows:
  tmp={}
  foe y in range(len(cols)):
  tep

[{'New Charges': 'Bar Charges', 'From': '12/29/19', 'To': '12/29/19', 'Quantity': '1.00', 'Rate': '$71.65', 'Frequency': 'One time', 'Amount': '$71.65'}, {'New Charges': 'Dining Services', 'From': '12/31/19', 'To': '12/31/19', 'Quantity': '1.00', 'Rate': '$17.90', 'Frequency': 'One time', 'Amount': '$17.90'}, {'New Charges': 'Incontinence supplies', 'From': '12/18/19', 'To': '12/18/19', 'Quantity': '1.00', 'Rate': '$55.32', 'Frequency': 'One time', 'Amount': '$55.32'}, {'New Charges': 'Bar Charges', 'From': '01/11/20', 'To': '01/11/20', 'Quantity': '1.00', 'Rate': '$73.75', 'Frequency': 'One time', 'Amount': '$73.75'}, {'New Charges': 'Room - Assisted Living', 'From': '02/01/20', 'To': '02/29/20', 'Quantity': '1.00', 'Rate': '$4,695.00', 'Frequency': 'Monthly', 'Amount': '$4,695.00'}, {'New Charges': 'Assisted Living Level 3', 'From': '02/01/20', 'To': '02/29/20', 'Quantity': '1.00', 'Rate': '$1,700.00', 'Frequency': 'Monthly', 'Amount': '$1,700.00'}, {'New Charges': 'Basic Medication Management', 'From': '02/01/20', 'To': '02/29/20', 'Quantity': '1.00', 'Rate': '$275.00', 'Frequency': 'Monthly', 'Amount': '$275.00'}, {'New Charges': 'Emergency Response Charge', 'From': '02/01/20', 'To': '02/29/20', 'Quantity': '1.00', 'Rate': '$30.00', 'Frequency': 'Monthly', 'Amount': '$30.00'}]

In [51]:
cols=string1_dict[0]['table']['cols']
all_rows=string1_dict[0]['table']['rows']
res=[]
for x in all_rows:
  tmp={}
  for y in range(len(cols)):
    tmp[cols[y]]=x[y]
  res.append(tmp)
      for y in range(len(table)):
        tmp[cols[y]]=x[y]
      res.append(tmp)
print(res)

IndentationError: ignored

In [46]:
#res=[]
#tmp={}
for i in string1_dict:
  cols=string1_dict[0:]['table']['cols']
  all_rows=string1_dict[0:]['table']['rows']
  print(i)
  res=[]
  for x in all_rows:
    tmp={}
  for y in range(len(cols)):
    tmp[cols[y]]=x[y]
  res.append(tmp)
print(res)

IndentationError: ignored

In [66]:
for i in string1_dict:
  cols=string1_dict[0]['table']['cols']
  all_rows=string1_dict[0]['table']['rows']
  #print(i)
  var=[]
  var.append(i)
print(var)

NameError: ignored

In [82]:
final=[]
for i in range(len(string1_dict)):
  cols=string1_dict[i]['table']['cols']
  all_rows=string1_dict[i]['table']['rows']
  #print(i)
  res=[]
  for x in all_rows:
    tmp={}
    for y in range(len(cols)):
      tmp[cols[y]]=x[y]
    res.append(tmp)
  final.append(res)
print(final)

[[{'New Charges': 'Bar Charges', 'From': '12/29/19', 'To': '12/29/19', 'Quantity': '1.00', 'Rate': '$71.65', 'Frequency': 'One time', 'Amount': '$71.65'}, {'New Charges': 'Dining Services', 'From': '12/31/19', 'To': '12/31/19', 'Quantity': '1.00', 'Rate': '$17.90', 'Frequency': 'One time', 'Amount': '$17.90'}, {'New Charges': 'Incontinence supplies', 'From': '12/18/19', 'To': '12/18/19', 'Quantity': '1.00', 'Rate': '$55.32', 'Frequency': 'One time', 'Amount': '$55.32'}, {'New Charges': 'Bar Charges', 'From': '01/11/20', 'To': '01/11/20', 'Quantity': '1.00', 'Rate': '$73.75', 'Frequency': 'One time', 'Amount': '$73.75'}, {'New Charges': 'Room - Assisted Living', 'From': '02/01/20', 'To': '02/29/20', 'Quantity': '1.00', 'Rate': '$4,695.00', 'Frequency': 'Monthly', 'Amount': '$4,695.00'}, {'New Charges': 'Assisted Living Level 3', 'From': '02/01/20', 'To': '02/29/20', 'Quantity': '1.00', 'Rate': '$1,700.00', 'Frequency': 'Monthly', 'Amount': '$1,700.00'}, {'New Charges': 'Basic Medication Management', 'From': '02/01/20', 'To': '02/29/20', 'Quantity': '1.00', 'Rate': '$275.00', 'Frequency': 'Monthly', 'Amount': '$275.00'}, {'New Charges': 'Emergency Response Charge', 'From': '02/01/20', 'To': '02/29/20', 'Quantity': '1.00', 'Rate': '$30.00', 'Frequency': 'Monthly', 'Amount': '$30.00'}], [{'Payments': 'Electronic payment', 'Date': '12/30/19', '': '$6,997.32One time', 'Amount': '($6,997.32)'}], [{'Credits': 'n/a', 'From': 'n/a', 'To': 'n/a', 'Quantity': 'n/a', 'Rate': 'n/a', 'Frequency': 'n/a', 'Amount': '$0.00'}]]

In [32]:
v='string1_dict'
print()

string1_dict

In [7]:
print(res[0])

{'New Charges': 'Bar Charges', 'From': '12/29/19', 'To': '12/29/19', 'Quantity': '1.00', 'Rate': '$71.65', 'Frequency': 'One time', 'Amount': '$71.65'}

In [ ]:
syonym_dict = {"date":["From"], "description":["New Charges", "Services Description", "Description"], "qty":["Quantity", "Hours", "Qty"], "rate":["Rate", "Pay Rate", "Rate"], "amount":["Amount", "Total", "Amount"]}
date_re = re.compile("|".join(syonym_dict["date"]))
desc_re = re.compile("|".join(syonym_dict["description"]))
qty_re = re.compile("|".join(syonym_dict["qty"]))
rate_re = re.compile("|".join(syonym_dict["rate"]))
amount_re = re.compile("|".join(syonym_dict["amount"]))

In [14]:
cols=string1_dict[0]['table']['cols']
all_rows=string1_dict[0]['table']['rows']
res=[]
for x in all_rows:
  tmp={}
  for y in range(len(cols)):
    tmp[cols[y]]=x[y]
  res.append(tmp)
print(res)

[{'New Charges': 'Bar Charges', 'From': '12/29/19', 'To': '12/29/19', 'Quantity': '1.00', 'Rate': '$71.65', 'Frequency': 'One time', 'Amount': '$71.65'}, {'New Charges': 'Dining Services', 'From': '12/31/19', 'To': '12/31/19', 'Quantity': '1.00', 'Rate': '$17.90', 'Frequency': 'One time', 'Amount': '$17.90'}, {'New Charges': 'Incontinence supplies', 'From': '12/18/19', 'To': '12/18/19', 'Quantity': '1.00', 'Rate': '$55.32', 'Frequency': 'One time', 'Amount': '$55.32'}, {'New Charges': 'Bar Charges', 'From': '01/11/20', 'To': '01/11/20', 'Quantity': '1.00', 'Rate': '$73.75', 'Frequency': 'One time', 'Amount': '$73.75'}, {'New Charges': 'Room - Assisted Living', 'From': '02/01/20', 'To': '02/29/20', 'Quantity': '1.00', 'Rate': '$4,695.00', 'Frequency': 'Monthly', 'Amount': '$4,695.00'}, {'New Charges': 'Assisted Living Level 3', 'From': '02/01/20', 'To': '02/29/20', 'Quantity': '1.00', 'Rate': '$1,700.00', 'Frequency': 'Monthly', 'Amount': '$1,700.00'}, {'New Charges': 'Basic Medication Management', 'From': '02/01/20', 'To': '02/29/20', 'Quantity': '1.00', 'Rate': '$275.00', 'Frequency': 'Monthly', 'Amount': '$275.00'}, {'New Charges': 'Emergency Response Charge', 'From': '02/01/20', 'To': '02/29/20', 'Quantity': '1.00', 'Rate': '$30.00', 'Frequency': 'Monthly', 'Amount': '$30.00'}]